#!/usr/bin/env python3
"""Write a secrets.h full of random values, for testing a build against one.

A build against the committed `secrets.example.h` proves the fallback compiles.
It does not prove the build is indifferent to what the values ARE -- an accidental
dependency on a specific length, a character the preprocessor treats specially, or
a value some code compares against would all survive that test, because the
example file never changes.

This writes a throwaway secrets.h with random values of realistic shape, so the
build is exercised against something it has never seen. Nothing here is a
credential: the values are generated, used to compile, and thrown away.

Usage:
    python scripts/gen_test_secrets.py --output include/secrets.h
    python scripts/gen_test_secrets.py --output include/secrets.h --seed 7

The generated file is gitignored by the repository's `secrets.h*` rule, and this
script refuses to overwrite an existing file unless --force is given, so it
cannot quietly destroy a real one.
"""

from __future__ import annotations

import argparse
import random
import secrets
import string
import sys
from pathlib import Path

# Characters that are safe inside a C string literal and plausible in the real
# thing. No backslash or double quote: a real password could contain them, but a
# generator that emitted one would be testing the generator, not the firmware.
PASSWORD_ALPHABET = string.ascii_letters + string.digits + "-_.!@#%^&*+=?"
SSID_ALPHABET = string.ascii_letters + string.digits + " -_"


def rand_text(rng: random.Random, alphabet: str, lo: int, hi: int) -> str:
    return "".join(rng.choice(alphabet) for _ in range(rng.randint(lo, hi))).strip()


def rand_host(rng: random.Random) -> str:
    """Half the time an mDNS name, half the time a private IPv4 address."""
    if rng.random() < 0.5:
        label = "".join(rng.choice(string.ascii_lowercase) for _ in range(rng.randint(3, 12)))
        return f"{label}.local"
    return f"192.168.{rng.randint(0, 255)}.{rng.randint(1, 254)}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", required=True, help="path to write, e.g. include/secrets.h")
    ap.add_argument("--seed", type=int, help="make the output reproducible")
    ap.add_argument("--force", action="store_true", help="overwrite an existing file")
    args = ap.parse_args()

    out = Path(args.output)
    if out.exists() and not args.force:
        print(
            f"gen_test_secrets: {out} exists. Refusing to overwrite it without --force,\n"
            f"                  because it may be the real one.",
            file=sys.stderr,
        )
        return 2

    # Seeded for reproducibility when asked, cryptographically seeded otherwise --
    # so an unseeded run genuinely differs from the last one.
    rng = random.Random(args.seed if args.seed is not None else secrets.randbits(64))

    values = {
        "SECRET_OTA_PASSWORD": rand_text(rng, PASSWORD_ALPHABET, 8, 40),
        "SECRET_OTA_HOST_TX": rand_host(rng),
        "SECRET_OTA_HOST_RX": rand_host(rng),
        "SECRET_OTA_HOST_HH": rand_host(rng),
        "SECRET_SK_SERVER_ADDRESS": rand_host(rng),
        "SECRET_WIFI_SSID": rand_text(rng, SSID_ALPHABET, 1, 32),
        "SECRET_WIFI_PASSWORD": rand_text(rng, PASSWORD_ALPHABET, 8, 63),
        "SECRET_WIFI_SSID_2": rand_text(rng, SSID_ALPHABET, 1, 32),
        "SECRET_WIFI_PASSWORD_2": rand_text(rng, PASSWORD_ALPHABET, 8, 63),
        "SECRET_WIFI_SSID_3": "",
        "SECRET_WIFI_PASSWORD_3": "",
    }
    port = rng.choice([80, 3000, 3443, 8080, rng.randint(1024, 65535)])

    body = [
        "#pragma once",
        "",
        "// GENERATED BY scripts/gen_test_secrets.py -- THROWAWAY TEST DATA.",
        "//",
        "// Every value below is random. None of it is a credential, and none of it",
        "// reaches any real network. It exists so a build can be exercised against",
        "// values it has never seen, rather than only against the fixed placeholders",
        "// in secrets.example.h.",
        "//",
        "// If you are reading this in a working tree you care about, you have",
        "// overwritten your real secrets.h. Restore it before flashing anything.",
        "",
    ]
    for name, value in values.items():
        body.append(f'#define {name} "{value}"')
    body.append(f"#define SECRET_SK_SERVER_PORT {port}")
    body.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(body), encoding="utf-8")

    # Lengths, not values: the point is to show the shape was varied, and a test
    # log is not a place to print even a generated password.
    print(f"gen_test_secrets: wrote {out}")
    for name, value in values.items():
        print(f"  {name:<26} {len(value):>2} chars")
    print(f"  {'SECRET_SK_SERVER_PORT':<26} {port}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
